task: sr
model:
  name: svfocussrnet
  scale: 2
  dim: 32
  n_resblocks: 8
  use_advanced_rep: false

data:
  type: eo
  train_root: /mnt/data_server/etc/jshong/SuperResolution/Pretrained_Dataset/train/
  val_hr_root: /mnt/data_server/etc/jshong/SuperResolution/Pretrained_Dataset/val/HR
  val_lr_root: /mnt/data_server/etc/jshong/SuperResolution/Pretrained_Dataset/val/LRx2

train:
  epochs: 100
  batch_size: 16
  lr: 5e-5
  num_workers: 4
  gradient_accumulation_steps: 2
  patch_size: 256
  save_interval: 20
  
  # 저장 폴더 이름 지정 (옵션)
  # 설정 시 checkpoints/{save_name} 폴더에 저장됩니다. (설정하지 않으면 날짜시간 자동생성)
  save_name: "finetune_svfocussrnet_eo_sr_x2_dim32_epoch100_bs16_ga_2_lr5e-5_charbonnier_perceptual_edge_ssim_tv_260309" # 예: "experiment_v1"

  # Finetuning 설정
  # resume: 체크포인트에서 학습을 재개 (Epoch, Optimizer 상태 포함) -> 커맨드라인 인자 --resume 사용
  # pretrained_path: 특정 모델 가중치만 불러와서 새로 학습 (Epoch 1부터 시작) -> 아래 경로 설정
  pretrained_path: "checkpoints/train_svfocussrnet_sr_x2_dim32_block8epoch300_bs64_lr1e-4_charbonnier_260309/best.pth" # 예: "checkpoints/my_model/best.pth"
  
  # Optimizer 설정 (Adam, AdamW, SGD)
  optimizer:
    type: AdamW
    betas: [0.9, 0.999]
    # momentum: 0.9 # SGD 사용 시 필요
    
  weight_decay: 0.0
  grad_clip: 1.0

  # Early Stopping (Optional)
  early_stopping:
    patience: 10      # 개선 없는 Epoch 허용 횟수
    min_delta: 0.0001 # 최소 개선 폭 (Loss)

  # Scheduler 설정 (ReduceLROnPlateau, StepLR, CosineAnnealingLR)
  scheduler:
    # 1. ReduceLROnPlateau (Loss 기반 감소)
    # type: ReduceLROnPlateau
    # patience: 20
    # factor: 0.5
    
    # 2. StepLR (일정 Step 마다 감소)
    # type: StepLR
    # step_size: 50
    # gamma: 0.5

    # 3. CosineAnnealingLR (코사인 곡선 따라 감소)
    type: CosineAnnealingLR
    T_max: 100 # 보통 전체 Epoch 수와 맞춤
    eta_min: 1e-7 # 최소 Learning Rate
    
    
loss:
  l1:
    enabled: false
    weight: 1.0
  charbonnier:
    enabled: true
    weight: 1.0      # Stage 1에서 잡은 픽셀 정확도 유지 (Anchor 역할)
  perceptual:
    enabled: true
    weight: 0.01     # 핵심 수정: 기존 1.0에서 1/100 수준으로 낮춤. 자연스러운 질감 부여
  edge:
    enabled: true
    weight: 0.05     # Perceptual이 이미 디테일을 살리므로, Edge는 아주 약하게만 보조
    mode: 'gray'
  ssim:
    enabled: true
    weight: 0.1      # 전체적인 구조와 밝기 밸런스 유지
  tv:
    enabled: true
    weight: 0.005    # Perceptual로 인해 생길 수 있는 불필요한 노이즈 억제 (영상 떨림 방지)

export_onnx: false
