task: denoise
model:
  name: quicksrnet_denoise_opt # Using same backbone for denoise
  scale: 1
  dim: 32
  mode: medium

data:
  type: eo
  train_root: /mnt/data_server/etc/jshong/SuperResolution/Pretrained_Dataset/train/
  val_hr_root: /mnt/data_server/etc/jshong/SuperResolution/Pretrained_Dataset/val_denoise/HR
  val_lr_root: /mnt/data_server/etc/jshong/SuperResolution/Pretrained_Dataset/val_denoise/LR

train:
  epochs: 250
  batch_size: 48
  lr: 5e-5
  num_workers: 8
  patch_size: 256
  save_interval: 20
  
  # 저장 폴더 이름 지정 (옵션)
  # 설정 시 checkpoints/{save_name} 폴더에 저장됩니다. (설정하지 않으면 날짜시간 자동생성)
  save_name: "finetune_quickdenoiseopt_denoise_x1_dim32_epoch250_bs_48_lr_5e-5" # 예: "experiment_v1"

  # Finetuning 설정
  # resume: 체크포인트에서 학습을 재개 (Epoch, Optimizer 상태 포함) -> 커맨드라인 인자 --resume 사용
  # pretrained_path: 특정 모델 가중치만 불러와서 새로 학습 (Epoch 1부터 시작) -> 아래 경로 설정
  pretrained_path: "checkpoints/train_quickdenoiseopt_denoise_x1_dim32_epoch500_bs_48_lr_1e-4/best.pth" # 예: "checkpoints/my_model/best.pth"

  # Optimizer 설정 (Adam, AdamW, SGD)
  optimizer:
    type: AdamW
    betas: [0.9, 0.999]
    # momentum: 0.9 # SGD 사용 시 필요
    
  weight_decay: 1e-4
  grad_clip: 1.0

  # Scheduler 설정 (ReduceLROnPlateau, StepLR, CosineAnnealingLR)
  scheduler:
    # 1. ReduceLROnPlateau (Loss 기반 감소)
    # type: ReduceLROnPlateau
    # patience: 20
    # factor: 0.5
    
    # 2. StepLR (일정 Step 마다 감소)
    # type: StepLR
    # step_size: 50
    # gamma: 0.5

    # 3. CosineAnnealingLR (코사인 곡선 따라 감소)
    type: CosineAnnealingLR
    T_max: 800 # 보통 전체 Epoch 수와 맞춤
    eta_min: 1e-7 # 최소 Learning Rate

loss:
  l1:
    enabled: false
    weight: 1.0
  charbonnier:
    enabled: true
    weight: 1.0
  edge:
    enabled: false
    weight: 0.5
    mode: 'gray'
  ssim:
    enabled: false
    weight: 0.1
  perceptual:
    enabled: true
    weight: 0.05

export_onnx: false
