data:
  train_root: /mnt/data_server/etc/jshong/SuperResolution/Pretrained_Dataset/train/
  type: eo
  val_hr_root: /mnt/data_server/etc/jshong/SuperResolution/Pretrained_Dataset/val/HR
  val_lr_root: /mnt/data_server/etc/jshong/SuperResolution/Pretrained_Dataset/val/LRx4
data_config:
  crop_size: 256
  dataset_type: sr
  degradation:
    stage1:
      blur:
        betag:
        - 0.5
        - 4.0
        betap:
        - 1.0
        - 2.0
        enabled: true
        kernel_probs:
        - 0.45
        - 0.25
        - 0.12
        - 0.03
        - 0.12
        - 0.03
        kernel_sizes:
        - 7
        - 9
        - 11
        - 13
        - 15
        - 17
        - 19
        - 21
        prob: 0.5
        sigma:
        - 0.2
        - 3.0
      gaussian_noise:
        enabled: true
        gray_prob: 0.5
        prob: 0.5
        sigma_max: 5
        sigma_min: 1
      jpeg:
        enabled: true
        prob: 0.5
        quality_max: 95
        quality_min: 85
      poisson_noise:
        enabled: true
        gray_prob: 0.5
        prob: 0.5
        scale_max: 3.0
        scale_min: 0.05
      resize:
        enabled: true
        interpolations:
        - cv2.INTER_LINEAR
        - cv2.INTER_CUBIC
        - cv2.INTER_AREA
        prob: 0.7
        scale_max: 1.0
        scale_min: 0.5
      sinc:
        enabled: true
        kernel_sizes:
        - 7
        - 9
        - 11
        - 13
        - 15
        - 17
        - 19
        - 21
        prob: 0.1
    stage2:
      blur:
        betag:
        - 0.5
        - 4.0
        betap:
        - 1.0
        - 2.0
        enabled: true
        kernel_probs:
        - 0.45
        - 0.25
        - 0.12
        - 0.03
        - 0.12
        - 0.03
        kernel_sizes:
        - 7
        - 9
        - 11
        - 13
        - 15
        - 17
        - 19
        - 21
        prob: 0.5
        sigma:
        - 0.2
        - 1.5
      common_noise:
        enabled: true
        gray_prob: 0.2
        prob: 0.0
        sigma_max: 10
        sigma_min: 1
      final_jpeg:
        enabled: true
        prob: 0.8
        quality_max: 90
        quality_min: 50
      ir_noise:
        enabled: false
        non_uniformity:
          amp_max: 0.3
          amp_min: 0.1
          prob: 0.5
        thermal_noise:
          gray_prob: 0.9
          sigma_max: 20
          sigma_min: 5
        vertical_line:
          intensity_max: 10
          intensity_min: 2
          prob: 0.5
      target_resize:
        enabled: true
        interpolations:
        - cv2.INTER_CUBIC
        - cv2.INTER_LINEAR
        - cv2.INTER_LANCZOS4
  use_flip: true
  use_rot: true
data_config_path: configs/data/sr_finetune_eo.yaml
export_onnx: false
loss:
  charbonnier:
    enabled: true
    weight: 1.0
  edge:
    enabled: true
    mode: gray
    weight: 0.05
  l1:
    enabled: false
    weight: 1.0
  perceptual:
    enabled: true
    weight: 0.01
  ssim:
    enabled: true
    weight: 0.1
  tv:
    enabled: true
    weight: 0.005
model:
  dim: 32
  n_resblocks: 8
  name: svfocussrnet
  scale: 4
  use_advanced_rep: false
task: sr
train:
  batch_size: 16
  early_stopping:
    min_delta: 0.0001
    patience: 10
  epochs: 100
  grad_clip: 1.0
  gradient_accumulation_steps: 2
  lr: 5e-5
  num_workers: 4
  optimizer:
    betas:
    - 0.9
    - 0.999
    type: AdamW
  patch_size: 256
  pretrained_path: checkpoints/train_svfocussrnet_sr_x4_dim32_epoch300_bs_64_lr_1e-4/best.pth
  save_interval: 20
  save_name: finetune_svfocussrnet_eo_sr_x4_dim32_epoch100_bs_16_ga_2_lr_5e-5
  scheduler:
    T_max: 100
    eta_min: 1e-7
    type: CosineAnnealingLR
  weight_decay: 0.0
