task: denoise
model:
  name: svfocussrnet
  use_advanced_rep: false
  scale: 1
  dim: 24
  n_resblocks: 2

data:
  type: eo
  train_root:
    - /mnt/data_server/etc/jshong/SuperResolution/Pretrained_Dataset/train/
  val_hr_root: /mnt/data_server/etc/jshong/SuperResolution/Pretrained_Dataset/val_denoise/HR
  val_lr_root: /mnt/data_server/etc/jshong/SuperResolution/Pretrained_Dataset/val_denoise/LR

train:
  epochs: 180
  batch_size: 96
  lr: 2e-5
  num_workers: 4
  gradient_accumulation_steps: 1
  patch_size: 256
  save_interval: 20
  save_name: "finetune_svfocusdenoise_mc_g105_v1_x1_dim24_block2_260422"

  pretrained_path: "checkpoints/train_svfocusdenoise_basic_x1_dim24_block2_epoch300_lr5e-5_awgn_260420/best.pth"

  optimizer:
    type: AdamW
    betas: [0.9, 0.999]
  weight_decay: 1e-4
  grad_clip: 1.0

  early_stopping:
    patience: 40
    min_delta: 0.0
    monitor: 'psnr'
    mode: 'max'

  scheduler:
    type: CosineAnnealingLR
    T_max: 180
    eta_min: 1e-7

loss:
  charbonnier:
    enabled: true
    weight: 1.0
  edge:
    enabled: true
    weight: 0.12
    mode: 'gray'
  ssim:
    enabled: true
    weight: 0.15
  l1:
    enabled: false
    weight: 1.0
  perceptual:
    enabled: false
    weight: 0.0
  color_consistency:
    enabled: true
    weight: 0.08
    loss_type: 'charbonnier'
  hot_pixel_masked:
    enabled: true
    weight: 0.15
    threshold: 0.10
    base_loss: 'charbonnier'
    kernel_size: 3
  tv:
    enabled: false
    weight: 0.1

export_onnx: false
