task: denoise
model:
  name: svfocussrnet
  use_advanced_rep: false
  scale: 1
  dim: 32
  n_resblocks: 2

data:
  type: eo
  train_root:
    - /mnt/data_server/etc/jshong/SuperResolution/Pretrained_Dataset/train/
  val_hr_root: /mnt/data_server/etc/jshong/SuperResolution/Pretrained_Dataset/val_denoise/mc_g105_phase1_denoise_priority_v2_fixed/HR
  val_lr_root: /mnt/data_server/etc/jshong/SuperResolution/Pretrained_Dataset/val_denoise/mc_g105_phase1_denoise_priority_v2_fixed/LR

train:
  epochs: 320
  batch_size: 128
  lr: 5e-5
  num_workers: 4
  gradient_accumulation_steps: 1
  patch_size: 256
  save_interval: 20
  save_name: "train_svfocusdenoise_mc_g105_phase1_denoise_priority_v2_x1_dim32_block2_260515"

  pretrained_path: null

  optimizer:
    type: AdamW
    betas: [0.9, 0.999]
  weight_decay: 1e-4
  grad_clip: 1.0

  early_stopping:
    patience: 70
    min_delta: 0.00001
    monitor: 'loss'
    mode: 'min'

  scheduler:
    type: CosineAnnealingLR
    T_max: 320
    eta_min: 1e-7

loss:
  charbonnier:
    enabled: true
    weight: 1.0
  edge:
    enabled: true
    weight: 0.10
    mode: 'gray'
  ssim:
    enabled: true
    weight: 0.06
  l1:
    enabled: false
    weight: 1.0
  perceptual:
    enabled: false
    weight: 0.0
  color_consistency:
    enabled: true
    weight: 0.10
    loss_type: 'charbonnier'
  hot_pixel_masked:
    enabled: true
    weight: 0.22
    threshold: 0.08
    base_loss: 'charbonnier'
    kernel_size: 3
  tv:
    enabled: false
    weight: 0.0

export_onnx: false
